version: '3.9'
services:
  mysql:
    image: mysql:8.4
    container_name: blog-system-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: blog_system
    ports:
      - '3306:3306'
    volumes:
      - blog_system_mysql_data:/var/lib/mysql

volumes:
  blog_system_mysql_data:
